### ISSUE TITLE
Add new deno error messages

### ISSUE THREAD

**Issue by okcoker** [udibo/test_suite#16] opened 2022-02-20 08:42 UTC
Deno 1.19 added [better explanations](https://deno.com/blog/v1.19#better-errors-for-ops-and-resource-sanitizers-in-denotest) for leaking ops which are shown when using `Deno.test` but not when using `describe`/`it`

With Deno.test:

```
Test case is leaking async ops.

- 1 async operation to sleep for a duration was started before this test, but was completed during the test. Async operations should not complete in a test if they were not started in that test.

```

With describe/it:

```
AssertionError: Test case is leaking async ops.
Before:
- dispatched: 5
- completed: 4
After:
- dispatched: 36
- completed: 36
Make sure to await all promises returned from Deno APIs before
finishing test case.
    at assertEquals (https://deno.land/std@0.120.0/testing/asserts.ts:269:9)
    at assertOps (https://deno.land/x/test_suite@0.9.5/test_suite.ts:149:3)
    at async fn (https://deno.land/x/test_suite@0.9.5/test_suite.ts:482:28)
    at async testStepSanitizer (deno:runtime/js/40_testing.js:432:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:415:9)
    at async runTest (deno:runtime/js/40_testing.js:673:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:786:22)
```

**Comment by okcoker** [comment] 2022-02-20 09:01
Saw that 0.10.0 was released and decided to try it out. Now I'm getting an even more cryptic error for same test mentioned above.

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
        at asyncOpSanitizer (deno:runtime/js/40_testing.js:176:32)
        at async resourceSanitizer (deno:runtime/js/40_testing.js:360:7)
        at async exitSanitizer (deno:runtime/js/40_testing.js:415:9)
        at async TestContext.step (deno:runtime/js/40_testing.js:1039:13)
        at async Function.run (https://deno.land/x/test_suite@0.10.0/test_suite.ts:261:7)
        at async fn (https://deno.land/x/test_suite@0.10.0/test_suite.ts:109:13)
        at async testStepSanitizer (deno:runtime/js/40_testing.js:432:7)
        at async asyncOpSanitizer (deno:runtime/js/40_testing.js:145:9)
        at async resourceSanitizer (deno:runtime/js/40_testing.js:360:7)
        at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:415:9)
```

**Comment by okcoker** [comment] 2022-02-20 09:09
Actually that might have been a user error and I see the new error messages in 0.10.0.

Closing this out!

**Comment by okcoker** [comment] 2022-02-20 09:42
Ok actually there might be a problem here. 

Using this command: `deno test --allow-all --unstable src/ExifTool.spec.ts`

[All of the tests](https://github.com/okcoker/exiftool-vendored.js/blob/dad2281fa0e343cf97b16cd57b94a0ef5fd238b8/src/ExifTool.spec.ts) are passing except for the last one using test_suite v0.9.5

```
failures:

ExifTool parseJSON round-trips
AssertionError: Test case is leaking async ops.
Before:
- dispatched: 3049
- completed: 3048
After:
- dispatched: 3073
- completed: 3066
Make sure to await all promises returned from Deno APIs before
finishing test case.
    at assertEquals (https://deno.land/std@0.120.0/testing/asserts.ts:269:9)
    at assertOps (https://deno.land/x/test_suite@0.9.5/test_suite.ts:149:3)
    at async fn (https://deno.land/x/test_suite@0.9.5/test_suite.ts:482:28)
    at async testStepSanitizer (deno:runtime/js/40_testing.js:432:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:415:9)
    at async runTest (deno:runtime/js/40_testing.js:673:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:786:22)

failures:

	ExifTool parseJSON round-trips

test result: FAILED. 42 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (2m15s)
```

However on v0.10.0, I get a bunch of errors starting with the 3rd test, one of which is the error mentioned above in the last comment.

**Comment by KyleJune** [comment] 2022-02-20 15:05
I tried checking out that repository on the commit you linked to and am getting a failure related to module not being found. Looks like the issue preventing me from being able to run the tests locally is that you are depending on batch-cluster/mod.ts which exists in the parent directory.

```ts
kyle@kyle-XPS-15-9560:~/Projects/deno/exiftool-vendored$ deno test --allow-all --unstable src/ExifTool.spec.ts
Download https://cdn.skypack.dev/-/chai-subset@v1.6.0-OERewgkj4LWt51PakfUQ/dist=es2019,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/assert@v2.0.0-ENerrXlIB022hOhQfVwp/dist=es2019,mode=types/index.d.ts
error: Module not found "file:///home/kyle/Projects/deno/batch-cluster/mod.ts".
    at file:///home/kyle/Projects/deno/exiftool-vendored.js/src/deps.ts:6:31
```

If you make batch-cluster/mod.ts available, I could help with debugging this test issue to confirm whether it's an issue with test_suite or the code being tested.

**Comment by KyleJune** [comment] 2022-02-20 15:16
In the example from your start of this issue, it looks like 0.9.5 was working as expected. The reason the message is different is because 0.9.5 is using the older messaging for issues related to async ops. They recently updated the test runner to give a more detailed message for leaking ops related to timers. The 0.9.5 test coverage shows there was 1 more op dispatched than was closed. The new `deno.test` message appears to indicate that leaking async op is related to a timer being created but not resolving before the test finishes running.

**Comment by KyleJune** [comment] 2022-02-20 17:50
I looked at the callstack from your error using test_suite@0.10.0 and determined the issue is actually in Deno. The issue is caused by a leaking op in one of your tests. All I can say is the leaking op is not one of the operation types listed in [this OP_DETAILS object](https://github.com/denoland/deno/blob/v1.19.0/runtime/js/40_testing.js#L64). I believe the issue would be resolved if you downgrade to Deno 1.18.2 since the test hints were added in 1.19.0. You would still have a leaking op in your test but you would at least be able to figure out what the name of the op is.

I'm going to close this issue since it's been determined that the issue is not with this module. [Here](https://github.com/denoland/deno/issues/13729) is a new issue I created for this issue on the Deno repository.

**Closed as completed by KyleJune** 2022-02-20 17:50 UTC

**Comment by okcoker** [comment] 2022-02-20 19:42
> If you make batch-cluster/mod.ts available, I could help with debugging this test issue to confirm whether it's an issue with test_suite or the code being tested.

Sorry I should have mentioned this ahead of time but that is another project I am porting. They work together: https://github.com/okcoker/batch-cluster.js/tree/68655513a1844fedcf518d6986c3ccb19e3237fc

**Comment by KyleJune** [comment] 2022-02-20 19:50
> > If you make batch-cluster/mod.ts available, I could help with debugging this test issue to confirm whether it's an issue with test_suite or the code being tested.
> 
> Sorry I should have mentioned this ahead of time but that is another project I am porting. They work together: https://github.com/okcoker/batch-cluster.js/tree/68655513a1844fedcf518d6986c3ccb19e3237fc

It's all good, I was able to identify the issue was in Deno without actually reproducing it locally. The error call stack was enough for me to figure that out.

**Comment by KyleJune** [comment] 2022-02-25 06:10
I found an error in my code that might be causing an async op leak if you are using async hooks. The [latest release](https://github.com/udibo/test_suite/releases/tag/0.10.2) has a fix for that issue.

I recommend downgrading to Deno 1.18 until the issue with test steps is resolved in Deno 1.19. Luca responded to the issue I made on the Deno repo saying he knows what caused it and will fix it but I believe he is out of office until March 3rd.
